/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/thinking-with-portals.gltf 
*/
//@ts-nocheck

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { RigidBody, RapierRigidBody, MeshCollider, CuboidCollider } from '@react-three/rapier'

export function Cube(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/thinking-with-portals.gltf')
  
  if (!nodes || !materials) {
    return null;
  }

  return (
    <group {...props} dispose={null}>
      {nodes.Cube001 && <mesh geometry={nodes.Cube001.geometry} material={materials.Blue} />}
      {nodes.Cube001_1 && <mesh geometry={nodes.Cube001_1.geometry} material={materials.White} />}
      {nodes.Cube001_2 && <mesh geometry={nodes.Cube001_2.geometry} material={materials.Grey} />}
    </group>
  );
}

export function Panel(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/thinking-with-portals.gltf')
  
  if (!nodes || !materials) {
    return null;
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody
        name="Panel"
        type="fixed"
        scale={[1, 0.05, 1]}
      >
        {nodes.Cube005 && <mesh geometry={nodes.Cube005.geometry} material={materials.Top} />}
        {nodes.Cube005_1 && <mesh geometry={nodes.Cube005_1.geometry} material={materials.Sides} />}
      </RigidBody>
    </group>
  );
}

export function PanelHole(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/thinking-with-portals.gltf')
  
  // Add safety checks for nodes
  if (!nodes || !materials) {
    return null;
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody
        name="Panel"
        type="fixed"
        scale={[1, 0.05, 1]}
      >
        <MeshCollider type="trimesh">
          <mesh geometry={nodes.Cube_1.geometry} material={materials.Top} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials.Sides} />
        </MeshCollider>

      </RigidBody>
      
      {nodes.Portal && (
        <mesh 
          geometry={nodes.Portal.geometry} 
          material={materials['Material.002']} 
          scale={[0.611, 0.72, 0.871]}  
          position={[0, 0.05, 0]}
        />
      )}
    </group>
  );
}

export function PanelSlope(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/thinking-with-portals.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.05, 1]}>
        <mesh geometry={nodes.Shape001.geometry} material={materials.Top} />
        <mesh geometry={nodes.Shape001_1.geometry} material={materials.Sides} />
      </group>
    </group>
  );
}

export function PistonSurface(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/piston_surface.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
        <mesh geometry={nodes.Body_dmxpiston_lift_top_modeldmx_MESH.geometry} material={materials['AR/VR Glass for GLTF extension']} />
        <mesh geometry={nodes.Body_dmxpiston_lift_top_modeldmx_MESH_1.geometry} material={materials.platform} />
      </group>
    </group>
  );
}

export function FullScene(props) {
  const { nodes, materials } = useGLTF('/demos/portals/models/thinking-with-portals.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.491, 0]} scale={2.522}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Window} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.Metal2} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-1.836, 3.842, 1.965]} scale={[0.36, 0.507, 0.36]} />
      <group position={[-1.887, 2.422, 1.957]} rotation={[Math.PI / 2, 0, 0]} scale={0.335}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Grey} />
      </group>
      <group position={[-1.739, 2.97, -1.815]} rotation={[Math.PI / 2, 0, 0]} scale={0.335}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials.Grey} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-1.895, 3.213, 0.919]} rotation={[-Math.PI / 6, 0, 0]} scale={[0.39, 0.04, 0.39]} />
      <mesh geometry={nodes.Portal001.geometry} material={materials.PortalOrange} position={[-1.851, 3.308, 0.897]} rotation={[-Math.PI / 6, 0, 0]} scale={[0.19, 0.261, 0.275]} />
      <mesh geometry={nodes.Portal002.geometry} material={materials.PortalOrange} position={[-1.823, 1.701, 1.976]} rotation={[0, 1.571, 0]} scale={[0.19, 0.261, 0.275]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-2.21, 3.239, -1.805]} rotation={[0, 0, -Math.PI / 2]} scale={[0.39, 0.04, 0.39]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-1.895, 2.115, 0.922]} scale={[0.057, 1.092, 0.057]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Button} position={[1.956, 3.91, -1.907]} scale={[0.208, 0.057, 0.208]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Button} position={[-2.331, 4.347, -1.907]} rotation={[0, 0, -Math.PI / 2]} scale={[0.208, 0.057, 0.208]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-1.063, 2.266, 0.919]} rotation={[0, 0, -Math.PI / 6]} scale={[0.39, 0.04, 0.39]} />
      <mesh geometry={nodes.Portal005.geometry} material={materials.PortalOrange} position={[-1.018, 2.369, 0.918]} rotation={[Math.PI / 2, Math.PI / 3, -Math.PI / 2]} scale={[0.19, 0.261, 0.275]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-1.062, 1.666, 0.922]} scale={[0.057, 0.642, 0.057]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[2.023, 1.74, 0.919]} scale={[0.224, 0.04, 0.39]} />
      <mesh geometry={nodes.Portal003.geometry} material={materials.PortalOrange} position={[1.377, 3.096, -2.182]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.19, 0.261, 0.275]} />
    </group>
  )
}
useGLTF.preload('/demos/portals/models/portals.gltf')
useGLTF.preload('/demos/portals/models/thinking-with-portals.gltf');
useGLTF.preload('/demos/portals/models/portal-models.gltf');
useGLTF.preload('/demos/portals/models/piston_surface.gltf');
