/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/portals.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/portals.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0.483, 3.341, -0.041]} scale={2.522} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-0.369, 1.792, -1.442]} scale={[1.518, 0.847, 0.953]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-1.251, 5.351, 1.832]} scale={[0.36, 0.507, 0.36]} />
      <group position={[-1.262, 4.03, 1.846]} rotation={[0, 0, -0.419]} scale={[0.538, 0.027, 0.538]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Top} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Sides} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-1.288, 3.189, -0.028]} rotation={[Math.PI / 2, 0, 0]} scale={[0.349, 2.481, 0.349]} />
      <group position={[0.74, 2.227, 1.848]} rotation={[0, 0, Math.PI / 6]} scale={[0.5, 0.025, 0.5]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Top} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Sides} />
      </group>
      <group position={[-1.19, 1.041, 1.845]} scale={[0.538, 0.027, 0.538]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials.Top} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Sides} />
      </group>
      <group position={[-1.261, 4.952, 1.844]} rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Grey} />
      </group>
      <mesh geometry={nodes.Portal004.geometry} material={materials.PortalOrange} position={[-1.235, 4.098, 1.843]} rotation={[Math.PI / 2, 1.152, -Math.PI / 2]} scale={[0.25, 0.261, 0.375]} />
      <mesh geometry={nodes.Portal005.geometry} material={materials.PortalBlue} position={[0.735, 2.262, 1.859]} rotation={[-Math.PI / 2, Math.PI / 3, Math.PI / 2]} scale={[0.25, 0.261, 0.375]} />
      <mesh geometry={nodes.Portal006.geometry} material={materials.PortalOrange} position={[-1.21, 2.73, -1.432]} rotation={[0, 1.571, 0]} scale={[0.25, 0.261, 0.375]} />
      <mesh geometry={nodes.Portal001.geometry} material={materials.PortalBlue} position={[0.533, 2.319, -1.432]} rotation={[Math.PI / 2, Math.PI / 3, -Math.PI / 2]} scale={[0.25, 0.261, 0.375]} />
      <mesh geometry={nodes.Portal003.geometry} material={materials.PortalBlue} position={[2.07, 4.545, -2.418]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 0.261, 0.375]} />
      <mesh geometry={nodes.Portal002.geometry} material={materials.PortalOrange} position={[2.052, 0.98, -1.432]} scale={[0.25, 0.261, 0.375]} />
    </group>
  )
}

useGLTF.preload('./models/portals.gltf')
